In [2]:
# Initial imports
import requests
from dotenv import load_dotenv
import os 
import json
import pandas as pd

ModuleNotFoundError: No module named 'dotenv'

In [17]:
load_dotenv()

True

In [18]:
#Get API Key stored as variable
api_key = os.getenv("CENSUS_DATA_API_KEY")

In [19]:
#Check that key was retrieved
type(api_key)

str

In [24]:
# Define the base request URL
state_pop_url = "https://api.census.gov/data/2021/pep/population?get=NAME,POP_2021&for=state:*&key="

# Concatenate request_url and api_key. Store as new variable
request_url = state_pop_url + api_key

In [25]:
state_pop_df = pd.read_json(request_url)
state_pop_df.head()

              0         1      2
0          NAME  POP_2021  state
1      Oklahoma   3986639     40
2      Nebraska   1963692     31
3        Hawaii   1441553     15
4  South Dakota    895376     46

In [31]:
state_pop_df.rename(columns=state_pop_df.iloc[0]).loc[1:]

                    NAME  POP_2021 state
1               Oklahoma   3986639    40
2               Nebraska   1963692    31
3                 Hawaii   1441553    15
4           South Dakota    895376    46
5              Tennessee   6975218    47
6                 Nevada   3143991    32
7             New Mexico   2115877    35
8                   Iowa   3193079    19
9                 Kansas   2934582    20
10  District of Columbia    670050    11
11                 Texas  29527941    48
12              Missouri   6168187    29
13              Arkansas   3025891    05
14              Michigan  10050811    26
15         New Hampshire   1388992    33
16        North Carolina  10551162    37
17                  Ohio  11780017    39
18        South Carolina   5190705    45
19               Wyoming    578803    56
20            California  39237836    06
21          North Dakota    774948    38
22             Louisiana   4624047    22
23              Maryland   6165129    24
24              Delaware   1003384    10
25          Pennsylvania  12964056    42
26               Georgia  10799566    13
27                Oregon   4246155    41
28             Minnesota   5707390    27
29              Colorado   5812069    08
30            New Jersey   9267130    34
31              Kentucky   4509394    21
32            Washington   7738692    53
33                 Maine   1372247    23
34               Vermont    645570    50
35                 Idaho   1900923    16
36               Indiana   6805985    18
37               Montana   1104271    30
38              New York  19835913    36
39           Puerto Rico   3263584    72
40           Connecticut   3605597    09
41               Florida  21781128    12
42              Virginia   8642274    51
43         Massachusetts   6984723    25
44              Illinois  12671469    17
45           Mississippi   2949965    28
46               Arizona   7276316    04
47                  Utah   3337975    49
48             Wisconsin   5895908    55
49               Alabama   5039877    01
50         West Virginia   1782959    54
51          Rhode Island   1095610    44
52                Alaska    732673    02

In [34]:
state_pop_df.drop(columns='state', inplace=True)

KeyError: "['state'] not found in axis"

In [32]:
state_pop_df.set_index(state_pop_df['state'])

KeyError: 'state'

In [ ]:
# Define the base request URL
income_by_age_url = "https://api.census.gov/data/2021/cps/asec/mar?get=HEARNVAL&A_AGE&for=state:*&key="

# Concatenate request_url and api_key. Store as new variable
request_url = income_by_age_url + api_key

In [ ]:
income_by_age_df = pd.read_json(request_url)
income_by_age_df.head()